# Generated by Django 5.1.4 on 2025-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
