# Generated by Django 5.1.4 on 2025-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('L', 'Lagartija'), ('E', 'Eléctrico'), ('P', 'Planta'), ('F', 'Fuego'), ('A', 'Agua')], max_length=30),
        ),
    ]
